model_organization:    alliance-genome
model_name:            agr_curation_schema
root_schema: alliance-model  # the name of the base schema file (w/o .yaml)
model_root_class: GenomicEntity   # <name of the base class in the schema for testing

model_author:              Alliance of Genome Resources
model_author_email:        smoxon@lbl.gov, chris@wormbase.org, dossantos@morgan.harvard.edu, mqt@ebi.ac.uk
model_synopsis:  Model to describe the Alliance curation/persistence data store

# Trove Classifiers (https://pypi.org/classifiers/) -- these can be omitted if the elemens below are sufficient

# Keywords -- these can also be omitted from this file if the below is ok
keywords: [linkml, LOD, Modeling, Linked open data, model, Alliance, MOD]

# Elements to be generated
# See: https://github.com/linkml/linkml/generators/README.md for what the outputs look like
# Possible values: graphql -- graphql schema for the model
#                  json -- LinkML model definition in JSON syntax
#                  jsonld_context -- JSON-LD context definitions for model
#                  json_schema -- Model schema in json schema
#                  owl -- OWL representation of model schema
#                  rdf -- LinkML Model definition in RDF
#                  shex -- LinkML model definition in ShEx
#                  sqlddl -- SQL ddl of the model
#                  model -- copy model/schema to distribution directory
generate: [jsonld_context, json_schema, model]

