site_name: "Model to describe the Alliance curation/persistence data store"
theme:
  name: readthedocs
highlightjs: truechema assumes a property graph
plugins:
  - search

docs_dir: docs
site_dir: mkdocs_html

nav:
  - Browse the Model: index.md


site_url: https://github.com/alliance-genome/agr_curation_schema
repo_url: https://github.com/alliance-genome/agr_curation_schema

extra_css:
  - extra_css.css