site_name: "Alliance Persistent Store"
theme:
  name: material
plugins:
  - search
  - mermaid2


docs_dir: docs
site_dir: mkdocs_html

nav:
  - Browse the Model: index.md
  - Developing the Alliance Model: developing-the-model.md
  - LinkML Tutorial: https://linkml.io/linkml/intro/tutorial.html

site_url: https://github.com/alliance-genome/agr_curation_schema
repo_url: https://github.com/alliance-genome/agr_curation_schema
