site_name: "Model to describe the Alliance curation/persistence data store"
theme:
  name: material
plugins:
  - search
  - mermaid2


docs_dir: docs
site_dir: mkdocs_html

nav:
  - Browse the Model: index.md
  - Developing the Alliance Model: README.md
  - LinkML Tutorial: https://linkml.io/linkml/intro/tutorial.html


site_url: https://github.com/alliance-genome/agr_curation_schema
repo_url: https://github.com/alliance-genome/agr_curation_schema

extra_css:
  - extra_css.css