name: Build and Deploy Static Mkdocs Documentation

# Controls when the action will run. Triggers the workflow on pull request
on:
  push:
    branches:
      - main
    paths:
      - 'mkdocs.yml'
      - 'model/schema/*.yaml'

  repository_dispatch:
    types: trigger-build-deploy-documentation

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # Install pipenv
      - name: Install pipenv
        run: python3 -m pip install --no-cache-dir pipenv

      # If cache was not loaded, install dependencies
      - name: Install dependencies
        run: pipenv install -d

      - name: Make Artifacts
        run: |
          make clean-artifacts
          make all

      # generate markdown files
      - name: Stage docs
        run: make stage-docs

      # deploy documentation (note: requires documentation is in docs dir)
      - name: gh deploy
        run: make gh-deploy