name: Test PRs

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      - name: Install Poetry 1.x
        run: pipx install poetry==1.*

      - name: Install Dependencies
        run: poetry install --no-interaction --no-root

      - name: regenerate artifacts and validate against generated artifacts
        run: |
          make clean
          make all
          make test-jsonschema
